// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: DeleteDatabase.sql

package database

import (
	"context"
)

const deleteDatabase = `-- name: DeleteDatabase :exec

DELETE FROM users
`

func (q *Queries) DeleteDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDatabase)
	return err
}
