// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: DeleteUser.sql

package database

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :one

DELETE FROM users
WHERE name = $1
RETURNING id, created_at, updated_at, name
`

func (q *Queries) DeleteUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
