// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: FeedByUrl.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const feedByUrl = `-- name: FeedByUrl :one

SELECT id
FROM feeds
WHERE url = $1
`

func (q *Queries) FeedByUrl(ctx context.Context, url string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, feedByUrl, url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
