// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: FeedsDisplay.sql

package database

import (
	"context"
)

const feedsDisplay = `-- name: FeedsDisplay :many

SELECT feeds.name, feeds.url, users.name
FROM feeds
JOIN users ON users.id = feeds.user_id
`

type FeedsDisplayRow struct {
	Name   string
	Url    string
	Name_2 string
}

func (q *Queries) FeedsDisplay(ctx context.Context) ([]FeedsDisplayRow, error) {
	rows, err := q.db.QueryContext(ctx, feedsDisplay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedsDisplayRow
	for rows.Next() {
		var i FeedsDisplayRow
		if err := rows.Scan(&i.Name, &i.Url, &i.Name_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
