// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetPostsForUser.sql

package database

import (
	"context"
)

const getPostsForUser = `-- name: GetPostsForUser :many

SELECT title, description
FROM posts
ORDER BY updated_at
LIMIT $1
`

type GetPostsForUserRow struct {
	Title       string
	Description string
}

func (q *Queries) GetPostsForUser(ctx context.Context, limit int32) ([]GetPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForUserRow
	for rows.Next() {
		var i GetPostsForUserRow
		if err := rows.Scan(&i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
