// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Unfollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const unfollow = `-- name: Unfollow :exec

WITH feedToDelete AS (
    SELECT feed_follows.id
    FROM feed_follows
    JOIN feeds ON feed_follows.feed_id = feeds.id
    JOIN users ON feed_follows.user_id = users.id
    WHERE feeds.url = $1 AND users.id = $2
)

DELETE FROM feed_follows
WHERE id IN (SELECT id FROM feedToDelete)
`

type UnfollowParams struct {
	Url string
	ID  uuid.UUID
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollow, arg.Url, arg.ID)
	return err
}
