-- +goose Up

ALTER TABLE posts
ALTER COLUMN title SET NOT NULL,
ALTER COLUMN url SET NOT NULL,
ALTER COLUMN description SET NOT NULL,
ALTER COLUMN published_at SET NOT NULL;

-- +goose Down
ALTER TABLE posts
ALTER COLUMN title DROP NOT NULL,
ALTER COLUMN url DROP NOT NULL,
ALTER COLUMN description DROP NOT NULL,
ALTER COLUMN published_at DROP NOT NULL;